apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    database: telegraf
    user: telegraf
    password: pass
    url: http://192.168.10.111:8086
    is_default: true
    editable: true
    jsonData:
      httpMode: GET
